### ISSUE TITLE
NoteFailure.unexpected: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by derhelge** [ResoCoder/flutter-ddd-firebase-course#19]
Hi there,

first things first: A million thanks for the great tutorial.

I'm currently running into a bug that seems to affect this repository as well:

A call after login generates an unexpected error:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast

It seems that a feature in freezed is missing here?
https://github.com/rrousselGit/freezed/issues/292

I cant figure out a clean way to solve this issue.... Maybe its also a completely different problem (:

**Comment by derhelge** [comment]
Okay... Going for a walk helped me. My problem had nothing to do with the code base, but was triggered by Firestore: my data structure was wrong and that triggered the error. That's why the error message made complete sense.

**Comment by Waruna-Kaushalya** [comment]
@derhelge I'm stuck there too. How to get rid of this? What changes have you made to the data structure? 😔

**Comment by derhelge** [comment]
Hey @Waruna-Kaushalya i cant remember it 100% but i guess you missed one "sub-folder". Think of the Firebase database as a JSON file/dictionary, then you know how to set it up.

**Comment by Waruna-Kaushalya** [comment]
Thank you @derhelge . I'll Check.
