### ISSUE TITLE
[Question] about state in BLoC

### ISSUE THREAD

**Issue by jpiabrantes** [ResoCoder/flutter-ddd-firebase-course#2]
I don't see where the variables `state` is declared in the code. How does this work?

https://github.com/ResoCoder/flutter-ddd-firebase-course/blob/66102ccc14122893bd5b9ba35dbff2faeb813da8/lib/application/auth/sign_in_form/sign_in_form_bloc.dart#L39

**Comment by pedrohsampaioo** [comment]
State is a get provided by the "flutter_bloc" package. In the bloc classes, this is mentioned, in case you unravel the abstract class Bloc you will find it there. The State always has the function of saving the last state of the Bloc, see more at [https://www.youtube.com/watch?v=hTExlt1nJZI&t=2387s](url) !

> I don't see where the variables `state` is declared in the code. How does this work?
> 
> https://github.com/ResoCoder/flutter-ddd-firebase-course/blob/66102ccc14122893bd5b9ba35dbff2faeb813da8/lib/application/auth/sign_in_form/sign_in_form_bloc.dart#L39

![state](https://user-images.githubusercontent.com/59283297/80211647-72aea880-860c-11ea-90b7-1a5f3dc9ea05.png)
