### ISSUE TITLE
The getter 'key' was called on null. 

### ISSUE THREAD

**Issue by amitsingh6391** [ResoCoder/flutter-ddd-firebase-course#24]
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building Builder(dirty):
The getter 'key' was called on null.
Receiver: null
Tried calling: key

**Comment by amitsingh6391** [comment]
anyone have solution for this issue

**Comment by amitsingh6391** [comment]
if anyone have this error then simplie add 
inside your appwidget.dart
home: SplashPage()

**Comment by hensal** [comment]
did you solve this issue?
