### ISSUE TITLE
NoteRepository.watchAll() hangs

### ISSUE THREAD

**Issue by chstrong** [ResoCoder/flutter-ddd-firebase-course#8]
I have a strange bug. In below code of the NoteBloc: 
- the NoteWatcherState.loadInProgress is fired.
- I also see that the _noteRepository.watchAll function is executed.
- But it stays in the NoteWatcherState.loadInProgress and doesn't continue.
- There is no error at all.
- All the Authentication code works by the way, and I could retrieve a document from firestore directly from the notes_overview_page.

I built the app two times from scratch following the tutorial. I tried to debug, but the debug simply ignores everything after this line: _noteStreamSubscription = _noteRepository.watchAll().listen(

Does anybody know what could cause this? I'm somehow stuck without any errors or debug capabilities.

NoteWatcherBloc
```
   yield* event.map(
      watchAllStarted: (e) async* {
        yield const NoteWatcherState.loadInProgress();
        await _noteStreamSubscription?.cancel();
        _noteStreamSubscription = _noteRepository.watchAll().listen( // <-- debug doesn't go into here and simply ignores it
              (failureOrNotes) =>
                  add(NoteWatcherEvent.notesReceived(failureOrNotes)), // <-- this is not executed, no idea why, no error.
            );
      },
```

NoteRepository
```
 @override
  Stream<Either<NoteFailure, KtList<Note>>> watchAll() async* {
    final userDoc = await _firestore.userDocument();

    print("Its listening"); // <-- I see that this is printed when i reload

    yield* userDoc.noteCollection // <-- no idea if this is actually done
      .orderBy('serverTimeStamp', descending: true)
      .snapshots()
      .map((snapshot) => right<NoteFailure, KtList<Note>>(
        snapshot.documents
          .map((doc) => NoteDto.fromFirestore(doc).toDomain())
          .toImmutableList(),
      )
    )
    .onErrorReturnWith((e) { // <-- no error here. 
      if(e is PlatformException && e.message.contains('PERMISSION_DENIED')) {
        print("platformexception");
        return left(const NoteFailure.insufficientPermission());
      } else {
        // log.error(e.toString())
        print("unexpected");
        return left(const NoteFailure.unexpected());
      }
    });
  }
```

**Comment by chstrong** [comment]
Was an issue with the Firestore Rules.

**Comment by Meshkat-Shadik** [comment]
> Was an issue with the Firestore Rules.

@chstrong 
Same  Problem facing now!!
What are the procedures to overcome with this problem? 
Thanks
